services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###
  fpm:
    build:
      args:
        - BUILD_ENV=dev
    ports:
      - "9003"
###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    networks:
      - chamedanyar-net
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_SENDMAIL_SMTP_ADDR: mailer:1025
###< symfony/mailer ###

networks:
  chamedanyar-net: